services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    container_name: HangFireSqlPOC
    env_file:
      - .env
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=${MSSQL_ROOT_PASSWORD}
    ports:
     - "1456:1433"
    volumes:
     - ${HOME}/temp/HangFireSqlPOC:/var/opt/mssql/data